python train.py --train_data ../dataset/lyrics/proc/adele/train.txt \
                --test_data ../dataset/lyrics/proc/adele/test.txt \
                --seq_len 64 \
                --d_model 128 \
                --n_layer 1 \
                --gpu 0 \
                --batch 8 \
                --lr 3e-4 \
                --epoch 10 \
                --bidirectional \
                --ckpt ./model/model-adele.pth